use_frameworks!

platform :ios, '9.0'

target 'SwiftyShare_Example' do
  use_frameworks!
  
  pod 'SwiftyShare', :path => '../'
  pod 'SwiftyShare/Extension', :path => '../'
#  pod 'SwiftyShare/Platforms/WeChat', :path => '../'
#  pod 'SwiftyShare/Platforms/WeChat_NoPay', :path => '../'
  pod 'SwiftyShare/Platforms/QQ', :path => '../'

  target 'SwiftyShare_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    # pod 'Nimble-Snapshots' , '~> 8.0.0'
  end
end
